version: "3.6"


services:
  pg-auth-server:
    network_mode: host
    build:
      context: ./Authentication/
      dockerfile: Dockerfile
    container_name: pg-auth-server
    image: programmer-ground/auth-server
    ports:
      - 8080:8080

  pg-backend-server:
    network_mode: host
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    container_name: pg-backend-server
    image: programmer-ground/backend-server
    ports:
      - 9000:9000
  
  pg-front:
   network_mode: host
   build:
    context: ./Frontend/
    dockerfile: Dockerfile
   container_name: pg-front
   image: programmer-ground/front
   ports:
     - 3000:80
   depends_on: 
     - pg-auth-server
     - pg-backend-server
