server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

spring:
  application:
    name: pg-main-service

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/pg?characterEncoding=UTF-8&serverTimezone=UTC
    
management:
  endpoint:
    web:
      exposure:
        include: refresh, health, beans

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://pg-service-discovery:8761/eureka

file:
  dir: src/main/resource/images/
  playground-main-img: /pgmainimg/
  playground-description-img: /pgdesimg/
