version: "3.6"


services:
  pg-service-discorvery:
    image: programmer-ground/pg-euraka
    container_name: pg-service-discovery
    ports:
      - 8761:8761
    networks:
      - pg-infra_backend-proxy-net

  pg-api-gateway:
    restart: on-failure
    depends_on:
      - pg-service-discorvery
    container_name: pg-api-gateway
    image: programmer-ground/pg-gateway
    ports:
      - 8000:8000
    networks:
      - pg-infra_backend-proxy-net
    environment:
      - EUREKA_SERVICE_URL=http://pg-service-discorvery:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  pg-auth-server:
    depends_on:
      - pg-service-discorvery
      - pg-api-gateway
    container_name: pg-auth-server
    image: programmer-ground/pg-auth
    ports:
      - 8080:8080
    networks:
      - pg-infra_backend-proxy-net
    environment:
      - EUREKA_SERVICE_URL=http://pg-service-discorvery:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  pg-backend-server:
    depends_on:
      - pg-service-discorvery
      - pg-api-gateway
    container_name: pg-backend-server
    image: programmer-ground/pg-api
    ports:
      - 9000:9000
    networks:
      - pg-infra_backend-proxy-net
    environment:
      - EUREKA_SERVICE_URL=http://pg-service-discorvery:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

networks:
  pg-infra_backend-proxy-net:
    external: true

#  pg-front:
#   network_mode: host
#   build:
#    context: ./Frontend/
#    dockerfile: Dockerfile
#   container_name: pg-front
#   image: programmer-ground/front
#   ports:
#     - 3000:80
#   depends_on:
#     - pg-auth-server
#     - pg-backend-server
